---
- hosts: all
  remote_user: ubuntu
  become: yes # para logar como root

  tasks:
    - name: Install nginx
      # shell: sudo apt-get install nginx
      apt: # outra forma
        name: nginx
        state: present # precisa existir, se não existir. instalar (desinstalar = "absent"  )
        update_cache: yes # para o apt-get update antes do upt-get install

    - name: Init nginx
      # shell: sudo service nginx start
      service: # outra forma
        name: nginx
        state: started