---
# tasks file for install_nginx
- name: Install nginx
  # shell: sudo apt-get install nginx
  apt: # outra forma
    pkg:
    - nginx
    - nodejs
    - npm
    state: present # precisa existir, se não existir. instalar (desinstalar = "absent"  )
    update_cache: yes # para o apt-get update antes do upt-get install

- name: Init nginx
  # shell: sudo service nginx start
  service: # outra forma
    name: nginx
    state: started

# install express server and node app
- name: create dir /app
  file:
    path: /app
    state: directory
    
- name: copy package.json
  copy:
    src: package.json
    dest: /app/package.json

- name: npm Install
  npm:
    path: /app
    state: present

- name: copy index.js
  template:
    src: index.js.j2
    dest: /app/index.js

- name: copy app.service
  copy: 
    src: app.service
    dest: /etc/systemd/system/app.service

- name: enable app.service
  systemd:
    name: app
    enabled: yes

- name: run app service
  systemd:
    name: app
    state: started    

- name: copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: reload nginx
    